# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FriendTalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FriendTalk
  pod 'AFNetworking'
  pod 'AliRTCSdk'
  pod 'JSONModel'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'SVProgressHUD'

end
